### ISSUE TITLE
feat: Allow pages without front matter to be processed

### ISSUE THREAD

**Issue by nolder3193** [bridgetownrb/bridgetown#806] opened 2023-09-05 15:17 UTC
## Summary

Not sure if this is more of a bug or a feature request but I have a default layout applied to the `pages` collection in the site config which works fine but the page file itself still requires the 2 sets of triple dashed lines or else it 404s when trying to view it on the dev server. It would be nice if front matter wasn't required to process/build pages.

## Motivation

This would eliminate the need to include unnecessary code if your page(s) do not have the need for any front matter.

## Guide-level explanation

If, for example, the only front matter you were defining on your pages was the same layout over and over, you could simply define a default layout for your pages in the site config and eliminate the need for front matter in your pages entirely.

## Drawbacks

Only if it was technically not feasible for some reason.

## Unresolved Questions

N/A

**Comment by jaredcwhite** [comment] 2023-09-06 05:10
This is a duplicate of #515, and also definitely non-trivial to implement. (The difference between "resources" and "static files" is literally the presence of front matter.) For now, we'll need to keep the behavior as is.

**Closed by jaredcwhite** 2023-09-06 05:10 UTC
