### ISSUE TITLE
obfuscate_link liquid filter produces broken JS 

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown#249] opened 2021-02-17 22:33 UTC
When using obfuscate_link liquid filter in a MD file the output is invalid.

Eg in `page.md`, `{{ "info@example.com" | obfuscate_link }}` produces

`Unexpected token ';'. Expected ')' to end a compound expression.`

This seems to be because characters in the output are being HTML escaped:

```
<script type="text/javascript">document.currentScript.insertAdjacentHTML('beforebegin', 'k2 9C67lQ&gt;2:=E@i:?7@o6I2&gt;A=6]4@&gt;Qm:?7@o6I2&gt;A=6]4@&gt;k^2m'.replace(/[!-~]/g,function(c){{var j=c.charCodeAt(0);if((j&gt;=33)&amp;&amp;(j&lt;=126)){return String.fromCharCode(33+((j+ 14)%94));}else{return String.fromCharCode(j);}}}));</script>
```

**Bridgetown Version**:

0.19.3

**To Reproduce**
Markdown with `{{ "info@example.com" | obfuscate_link }}`

**Comment by jaredcwhite** [comment] 2021-02-17 22:35
Thanks for the heads up @stevegeek.

@julianrubisch Any chance you could take a peek at this?

**Comment by julianrubisch** [comment] 2021-02-20 19:09
I'll put it on my list 👍

**Comment by julianrubisch** [comment] 2021-02-21 13:53
It reminds me of the markdown-related issue I had 2 months ago: https://discord.com/channels/711236503493148733/711236503975624727/789393451468587088

**Comment by jaredcwhite** [comment] 2021-05-09 03:39
I'm not able to reproduce this, at least not in the 0.21 beta. Closing for now. Feel free to reopen if you can provide an example repo with the failure.

**Closed by jaredcwhite** 2021-05-09 03:39 UTC
Labels: bug
